### ISSUE TITLE
Bangi: uma plataforma EAD

### ISSUE THREAD

**Issue by fernandobagno** [dritc/ideas#7]
Atualmente existem cada vez mais centros de ensino optando por um ensino a distância (EAD). Com isso, também percebo que - ao menos em Brasília - estas instituições só tem duas opções: 1) usar o Moodle, que é *opensource* mas é preciso sempre ter alguém contratado com conhecimento em programação para customizar a plataforma e 2) o BlackBoard, que é uma plataforma EAD paga.

Daí me surgiu a ideia já há algum tempo de criar uma plataforma EAD que consiga atender bem às necessidades de seus usuários. Sejam eles docentes, alunos ou gestores da ferramenta, de forma que estes últimos não precisem despender verbas para pessoal simplesmente para customizar a ferramenta.

# O que é a ideia?

Criar uma plataforma EAD seguindo, claro, as boas práticas de programação e utilizando componentes e frameworks bastante utilizados no mercado (ZF2 + Doctrine 2 + Bootstrap 3 e MySQL) que contenha os seguintes casos de uso:

* Manter Usuário
* Manter Perfil
* Manter Aluno
* Manter Professor
* Manter Curso
* Manter Turma
* Manter Aula
* Manter Atividade
* Manter Questões e Respostas
* Manter Conteúdo de  Aula
* Manter Fórum
* Gerenciar Notas de Aluno
* Gerar Relatórios
* Gerenciar Plataforma

Claro, esses são os pensados até agora, pode ser que algum deixe de existir e que algum outro seja criado. Mas em resumo o sistema tem que contemplar estas funcionalidades.

## O que já tenho pronto?

Como é um projeto relativamente grande, tenho apenas um esboço do MER, o qual preciso melhorar e mudar aquilo que for preciso. Além disso, tenho 2 temas possíveis que podemos utilizar que foram adquiridos para outras atividades mas podem ser usados aqui também, evitando gastar tempo com layout. Já sobre código em si, não existe nada pronto. 

## O projeto já tem algum nome?

Sim. Até agora pensava no projeto sozinho, mas mudando um pouco minhas ideias resolvi que ele fosse *opensource*. De toda forma, o nome pensado é **Bangi** e antes que perguntem não tem relação com a cidade malaia, foi apenas um anagrama do meu sobrenome e a substituição da letra "o" pela letra "i". Gosto do nome por ser fácil de lembrar, mas pode muito bem ser mudado.

## E como monetizar isto?

Como todo projeto livre, com suporte, consultorias e evoluções pontuais.

É isso! 
E então, topam?

**Comment by douggr** [comment]
Seria algo *tipo* o moodle?

O @cristianoteles tem *knowhow* no assunto.

:+1:

**Comment by fernandobagno** [comment]
É, como o Moodle, mas com o principal de customização do sistema pelo próprio usuário. Acredito que este seria o principal foco da ideia.

**Comment by cristianoteles** [comment]
Para que um projeto com o nível de dedicação que esse projeto precisa é necessário ter um "cliente" ou alguém que tenha necessidades reais e que irá utilizar o sistema.
Ter alguém para usar o sistema é muito importante porque projetos sem aplicação real tendem a não vingar.
Existe o projeto Trilhas (https://github.com/preceptor) que pode ser um projeto mais avançado que esse e quem sabe vale mais a pena trabalhar nele do que criar um novo.

**Comment by fernandobagno** [comment]
É, de fato o projeto demandaria muita dedicação para ser realizado. Sobre o cliente, é meio difícil termos sempre um cliente antes de criamos alguma coisa, o que existe é a demanda de mercado e ela está crescente. De repente, essa expectativa de ter quem use antes de desenvolver pode ser a pedra no meio do caminho das ideias que vão ficando no esquecimento. 

Ps.: não conhecia o Trilhas, vou dar uma olhada com mais calma nele depois.

**Comment by fernandobagno** [comment]
Até porque, mesmo que o projeto demande certa mão de obra, percebemos que não é tanto assim. Por exemplo, mais da metade dos Casos de Uso são CRUD que são feitos numa lapada só. A atividade de maior complexidade seria modelar um banco que atenda as necessidades do projeto e o Caso de Uso Gerenciar Plataforma, que ainda deve ser pensado em quais as customizações possíveis para isso.

**Comment by douggr** [comment]
@robopets close `forgotten#all`

**Comment by douggr** [comment]
@fernandobagno conhece o codeschool? Acho que não que exista plataformas de
ensino parecidas com aquilo.

Com testes "práticos" como os que eles propoem. Seria um caso a se pensar?

Por exemplo, num teste de matemática, existem N maneiras de se chegar ao
resultado; a resposta de uma questão de história, por exemplo pode ter der
escrita de várias maneiras, chegando ao mesmo resultado, etc.

E já tenho várias outras idéias em mente.

Não tenho conhecimento/_knownhow_ em EAD, mas me garanto nos casos de uso
desenvolvimento tanto do backend quanto do frontend.

**Comment by renanbr** [comment]
Organizei algumas dúvidas-sugestões em tópicos para não bagunçar a mensagem.

#### Módulos
O formato dos módulos já está definida? Seria interessante que isso fosse bem pensado. Pelo que percebo as plataformas já possuem intrinsicamente idéias pré-estabelecidas sobre os conceitos de EAD. Então, quando isso é levado em conta, o responsável pela escolha da plataforma opta pela plataforma que mais se adapta às necessidades da instituição. Se a plataforma tiver uma engine (ou configuração) de módulos bem pensada a plataforma pode se comportar de mais adaptada à realidade da instituição, o que pode ser um diferencial entre as diversas ferramentas que já existem.

#### Padrões
Seria interessante que a plataforma trabalhasse com formatos padrões para por exemplo a importação e a exportação de informações, apenas para citar um caso. Não menos importante, seria interessante também a plataforma que permitisse que a captura dos dados - em formato padronizado - de maneira manual e também por APIs. Seguem alguns padrões de exemplo:
* LOM - Learning Object Metadata
* SCORM - Sharable Content Object Reference Model
* EML - Educational Modeling Language
* Tin Can

#### Customização pelo próprio usuário
A customização pelo que entendi seria na forma como a plataforma apresenta o conteúdo para o usuário (cores, posição de links em menu, atalhos?). Um curso de EAD possui, entre diversas outras características, o seu percurso/caminho pedagógico e os materiais didáticos. Essa customização afetaria também essas duas características que citei? Se sim, seria um diferencial e tanto em relação às outras plataformas, inclusive um desafio para a implementação de algo que permita isso.

**Comment by fernandobagno** [comment]
@renanbr tudo que tenho mesmo é a ideia passada aqui. Não defini muita coisa, até mesmo pois não sei dizer ainda se é viável demandarmos tempo ao desenvolvimento desta ideia sem saber ao certo se ela é viável ou não. Mas de toda forma, te respondo:

### Módulos
Quando penso em módulos é um pouco do que se tem hoje. Exatamente como disse com as ideias pré-estabelecidas sobre os conceitos EAD, mas também (ainda como você disse) com uma capacidade do usuário de poder adaptar a ferramenta à sua necessidade.

### Customização
A customização que pensei foi em relação aos cursos/disciplinas de uma instituição qualquer. Por exemplo, cada curso tem uma didática diferente, uma caminho que as vezes é até contrário ao "padrão" adotado na instituição, então a ferramenta deverá ser capaz de oferecer formas distintas para o tutor criar seu curso. Isso e, claro, as customizações básicas de links, cores, etc. 

### Padrões
Aqui é onde eu não pensei em nada ainda. Nem em padrões de código e nem em que o código poderá ser escrito. Não sei se deveríamos usar o ZF (1 ou 2) ou algum outro *framework* mais "sucinto" e que atenda a capacidade do projeto, qual BD, etc. O que é o motivo da exposição do projeto por aqui, para termos ideias de como fazê-lo e se devemos tentar isto.

**Comment by fernandobagno** [comment]
Depois de conversamos, percebemos realmente que como o @cristianoteles falou, é um esforço demasiado para algo incerto. Além disso, com o conhecimento do @renanbr na área entendemos melhor o motivo do sucesso do moodle e como as coisas funcionam com ele. Sendo assim, estou cancelando a ideia.

**Comment by renanbr** [comment]
Uma possível consequência dessa issue seria trabalhar as coisas que você @fernandobagno sente falta nas plataformas como moodle e fazer os módulos e plugins necessários.

**Comment by fernandobagno** [comment]
É, vou dar uma estudada melhor nestas plataformas. Obrigado pelas dicas amigo @renanbr!
