### ISSUE TITLE
robopets commands

### ISSUE THREAD

**Issue by douggr** [dritc/ideas#8]

**Comment by douggr** [comment]
@robopets close forgotten#all

**Comment by robopets** [comment]
@douggr nothing to do, Sir.

**Comment by douggr** [comment]
Ok, thanks

**Comment by robopets** [comment]
Sure! You are welcome.

**Comment by douggr** [comment]
This was not suppose to happen, @robopets.

**Comment by robopets** [comment]
What did you mean, @douggr?

**Comment by douggr** [comment]
@robopets go get some sleep. I'll fix you later.

**Comment by robopets** [comment]
Sure! :sleeping:

**Comment by douggr** [comment]
@robopets test

**Comment by douggr** [comment]
@robopets ping

**Comment by robopets** [comment]
Okay @douggr, I'm on it!

**Comment by robopets** [comment]
@douggr tested?

**Comment by robopets** [comment]
@douggr pong

**Comment by douggr** [comment]
LMVTFY Take 1: http://jsfiddle.net/V49NM/
