### ISSUE TITLE
Nome

### ISSUE THREAD

**Issue by douggr** [dritc/ideas#9]
Gostaria que todos participassem, mesmo que pouco, mas _ativamente_ dessa _comunidade_.

Entendo que todos trabalham e as vezes não tem tempo a "perder", mas a participação com idéias,
freelas, sugestões, informações, etc. seria um _plus_ para todos que trabalham e/ou utilizam
ferramentas open-source.

Não quero ser o _dono_ de nada — ou ter meu nome estampado em qualquer lugar —, só quero
compartilhar conhecimento com vocês e gostaria, de volta, o conhecimento de todos compartilhado. 

Bem, o domínio dritc.io vence em 2 dias; o nome **dritc** foi algo randômico que saiu da minha
cabeça num belo dia de sol; alguém teria sugestões para de nome para a
_comunidade_/_organização_? e idéias para um ícone divertido? :smiley: 

Abraço

cc /@dritc/dritc

**Comment by fernandobagno** [comment]
Eu estou totalmente sem criatividade para nomes, mas poderia ser algo que tenha a ver com nossa nacionalidade. Sei lá, ando meio assim, querendo mais referências ao país (quando possível, claro).

**Comment by maykelsb** [comment]
Acho que nao precisa mudar. Tem uma idéia de logo em anexo (troquei dias letras de lugar sem querer, desculpe). Mas jah serve de rumo para alguem com as habilidades. ;)

Enviado via iPod

Em 18/02/2015, às 16:03, Fernando Bagno <notifications@github.com> escreveu:

**Comment by douggr** [comment]
@maykelsb nao veio o anexo Kekel

**Comment by fernandobagno** [comment]
Também é uma opção deixar como está. Não vejo problema também não. Mas se fosse pra mais dar, ficaria a sugestão de alguma referência ao Brasil como disse antes...

**Comment by douggr** [comment]
Não acho bacana colocar algo relacionado ao Brasil, país de m, deixa prá lá.

Vou deixar como está mesmo. Valeu :heart:

**Comment by fernandobagno** [comment]
Vaza do país então. :P

Atenciosamente,
*Fernando Araújo Bagno da Silva*
http://fernandobagno.com.br
(61) 9947-8764


*AVISO:*
*Esta mensagem de e-mail e seus anexos podem conter informação confidencial
e de propriedade material e são para uso exclusivo do destinatário.
Qualquer revisão, uso, divulgação, distribuição ou cópia desta transmissão
é proibida, salvo por ou em nome do destinatário.* *Se você recebeu esta
transmissão por erro, notifique o remetente e destrua este e-mail e
quaisquer anexos e todas as cópias, eletrônicas ou impressas**.*


Em 20 de fevereiro de 2015 15:33, Douglas Gontijo <notifications@github.com>
escreveu:
